name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]

jobs:
  # This workflow will create a new issue comment when a new pull request is opened using the github-script action
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on New Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for opening this pull request!'
            })
