name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        # using the action from the master branch of the repository "actions/hello-world-javascript-action"
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Earthy"
      # Use the output from the `Simple JS Action` step
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"
