name: Status Check
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on failure
        # Will only run if the previous step fails
        if: failure()
        run: echo "Runs only on failure"
      - name: Runs on success
        # This is not necessary, as it is the default behavior
        if: success()
        run: echo "Runs on success"
        # This step will always run weither the previous step fails or not
      - name: Always runs
        if: always()
        run: echo "Always runs"
      - name: Runs when cancelled
        if: cancelled()
        run: echo "Runs on cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
