name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - main # Will only trigger when the Repository Events workflow is completed on the main branch

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered after the Repository Events workflow was completed."
